{
  "success": true,
  "message": "Content is not HTML, skipping asset/metadata extraction.",
  "headers": {
    "accept-ranges": "bytes",
    "access-control-allow-origin": "*",
    "age": "0",
    "cache-control": "public, max-age=0, must-revalidate",
    "cf-cache-status": "REVALIDATED",
    "cf-ray": "9f5451a7fe67372d-FRA",
    "content-disposition": "inline; filename=\"registerSW.js\"",
    "content-length": "134",
    "content-type": "application/javascript; charset=utf-8",
    "date": "Sat, 02 May 2026 04:35:23 GMT",
    "etag": "\"1872c500de691dce40960bb85481de07\"",
    "last-modified": "Sat, 02 May 2026 03:07:33 GMT",
    "server": "cloudflare",
    "strict-transport-security": "max-age=63072000; includeSubDomains; preload",
    "x-vercel-cache": "HIT",
    "x-vercel-enable-rewrite-caching": "1",
    "x-vercel-id": "fra1::szrd7-1777691252887-e826b4a23d85"
  },
  "sourceCode": "if('serviceWorker' in navigator) {window.addEventListener('load', () => {navigator.serviceWorker.register('/sw.js', { scope: '/' })})}",
  "assets": {},
  "metadata": {},
  "requestedUrl": "https://shortpro.vercel.app/registerSW.js",
  "correctedUrl": "https://shortpro.vercel.app/registerSW.js",
  "finalUrl": "https://shortpro.vercel.app/registerSW.js",
  "status": 200,
  "statusText": "OK"
}
